### ISSUE TITLE
dubbo服务在nacos点击下线之后还能继续访问

### ISSUE THREAD

**Issue by wuxiaobo000111** [dubbo/dubbo-registry-nacos#10]
![image](https://user-images.githubusercontent.com/20573340/50596610-cd843400-0edf-11e9-9d65-a91e33edd483.png)
![image](https://user-images.githubusercontent.com/20573340/50596621-d4ab4200-0edf-11e9-8a40-c6c503b32f00.png)

nocos显示服务已经下线，但是该服务还是能够访问

**Comment by mercyblitz** [comment]
It will be fixed in https://github.com/apache/incubator-dubbo/issues/3296
