### ISSUE TITLE
spring cloud gateway discovery issues

### ISSUE THREAD

**Issue by misselvexu** [dubbo/dubbo-registry-nacos#12]
## Develop Env

| Framework Name | Version | Mark |
| --- | --- | --- |
| JDK | `1.8` | `OpenJDK` |
| Spring Boot | `2.0.5` | -  |
| Spring Cloud | `Finchley SR2` | -  |
| Apache Dubbo | `2.6.5` | -  |
| Alibaba Nacos | `0.7.0` | -  |
| Spring Cloud Alibaba | `0.2.1.RELEASE` | -  |

## Question

> Invalid dynamic route config
`lb://auth-provider`

Class `ServiceInstanceChooser` method param `serviceId ` naming rule is usually use `${spring.application.name}` 

Dubbo nacos registry service naming rule is generate with this method `getServiceName `
> NacosRegistry FROM `dubbo-registry-nacos`
```java
private String getServiceName(URL url, String category) {
        StringBuilder serviceNameBuilder = new StringBuilder(category);
        appendIfPresent(serviceNameBuilder, url, Constants.INTERFACE_KEY);
        appendIfPresent(serviceNameBuilder, url, Constants.VERSION_KEY);
        appendIfPresent(serviceNameBuilder, url, Constants.GROUP_KEY);
        return serviceNameBuilder.toString();
    }
```

> ServiceInstanceChooser FROM `spring-cloud-common`
```java

/**
 * Implemented by classes which use a load balancer to choose a server to
 * send a request to.
 *
 * @author Ryan Baxter
 */
public interface ServiceInstanceChooser {

    /**
     * Choose a ServiceInstance from the LoadBalancer for the specified service
     * @param serviceId the service id to look up the LoadBalancer
     * @return a ServiceInstance that matches the serviceId
     */
    ServiceInstance choose(String serviceId);
}

```

## Nacos Console
<img width="923" alt="image" src="https://user-images.githubusercontent.com/3436472/51020291-1790a800-15b9-11e9-9f59-eaea245df7c2.png">

## FIX
Change Dubbo Nacos Service Naming Rule
```java
private String getServiceName(URL url, String category) {
        return url.getParameter(Constants.APPLICATION_KEY); // application
}
```

Any other solution ?

**Comment by mercyblitz** [comment]
There are some different, this feature will be released in [spring-cloud-alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba).
