### ISSUE TITLE
does the registry  support spring-context 3.x?

### ISSUE THREAD

**Issue by libinglong** [dubbo/dubbo-registry-nacos#5]
please see the details

**Comment by mercyblitz** [comment]
What's the detail?

**Comment by libinglong** [comment]
> What's the detail?

when I searched the reason, I found i mistake the situation.
just reverse it.
when i use 
![image](https://user-images.githubusercontent.com/38123153/49947994-7a950d80-ff2d-11e8-8bf9-9039ec98a3b3.png) 3.2.18 as the "Getting started",it seems like the @PropertySource(value = "classpath:/provider-config.properties") doesn't work.
so the question should be change to does the registry support spring-context 3.2.18.RELEASE?
 @mercyblitz

**Comment by mercyblitz** [comment]
The spring-context 3.x just for Dubbo runtime, thus "getting started" gives a version range of Spring.
